name: Archive HuggingFace GGUF Models

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'HuggingFace model repo'
        required: true
        default: 'Qwen/Qwen2.5-Coder-3B-Instruct-GGUF'
        type: string
      file_filter:
        description: 'Filter pattern'
        required: true
        default: 'q8'
        type: string
      split_size:
        description: 'Split size in MB'
        required: false
        default: '800'
        type: string

jobs:
  download-gguf:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "huggingface_hub[cli]"
          choco install 7zip -y

      - name: Setup llama.cpp tools
        run: |
          $LATEST_URL = (Invoke-WebRequest -Uri "https://api.github.com/repos/ggerganov/llama.cpp/releases/latest" | ConvertFrom-Json).assets | Where-Object { $_.name -match "win-avx2-x64.zip" } | Select-Object -ExpandProperty browser_download_url
          Invoke-WebRequest -Uri $LATEST_URL -OutFile llama.zip
          Expand-Archive llama.zip -DestinationPath .
          Copy-Item "build\bin\llama-gguf-split.exe" -Destination "C:\Windows\System32"

      - name: Download GGUF files
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir D:\models
          huggingface-cli download ${{ github.event.inputs.model_name }} --include "*${{ github.event.inputs.file_filter }}*.gguf*" --local-dir D:\models

      - name: Get base name
        id: get_base_name
        run: |
          $BASE_NAME = (Get-ChildItem D:\models -Filter "*.gguf" | Select-Object -First 1).BaseName
          echo "base_name=$BASE_NAME" >> $env:GITHUB_OUTPUT

      - name: Merge split files
        run: |
          cd D:\models
          $SPLIT_FILES = Get-ChildItem -Filter "*-00001-of-*.gguf.*"
          if ($SPLIT_FILES.Count -gt 0) {
            $FIRST_SPLIT = $SPLIT_FILES[0]
            # Extract base name pattern (e.g. "model-q4_k_m" from "model-q4_k_m-00001-of-00014.gguf.1")
            $BASE_PATTERN = $FIRST_SPLIT.Name -replace '-00001-of-\d+\.gguf\.\d+$',''
            $TARGET_NAME = "$BASE_PATTERN.gguf"
            
            Write-Host "Merging $($FIRST_SPLIT.Name) to $TARGET_NAME"
            llama-gguf-split --merge $FIRST_SPLIT.Name $TARGET_NAME
            
            # Only remove split parts after successful merge
            Get-ChildItem -Filter "$BASE_PATTERN-*-of-*.gguf.*" | Remove-Item
          } else {
            Write-Host "No split files found, skipping merge"
          }

      - name: Create volumes
        run: |
          mkdir D:\volumes
          7z a -v${{ github.event.inputs.split_size }}m "D:\volumes\${{ steps.get_base_name.outputs.base_name }}.7z" "D:\models\*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_base_name.outputs.base_name }}-${{ github.sha }}
          name: ${{ steps.get_base_name.outputs.base_name }}
          files: D:/volumes/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}